### ISSUE TITLE
support for colors, bold etc. in the text-editor 

### ISSUE THREAD

**Issue by shirishag75** [stevenhoneyman/l3afpad#28]
I was looking at l3afpad and saw that both leafpad and l3afpad do not support colors in the text-editor - 

on the CLI - 

![maven-output-on-cli](https://user-images.githubusercontent.com/727626/45914139-49d99680-be5e-11e8-9a2a-b08e3c0c0208.png)

On l3afpad it's - 

![text-show-in-l3afpad](https://user-images.githubusercontent.com/727626/45914167-b785c280-be5e-11e8-97e6-3dedccc491ae.png)

**Comment by faraco** [comment]
Hi. Urm, this idea sounds cool but can you give us an example of any editor which does this?

**Comment by shirishag75** [comment]
There are many, just to name a few , `Atom`, lightable, brackets and even notepad++ .  All of these have syntax highlighting and what not. It would make

**Comment by hoijui** [comment]
[Syntax highlighting](https://en.wikipedia.org/wiki/Syntax_highlighting) is also a feature, that will not make it into l3afpad,
because it is not basic enough.
If you write it in a fork, it could be linked to from the main README though.
