### ISSUE TITLE
Does anybody of any ongoing alternatives to l3afpad which has active development ???

### ISSUE THREAD

**Issue by shirishag75** [stevenhoneyman/l3afpad#33]
Does anybody know of any alternatives to l3afpad that has active development. FWIW, l3afpad is now in Debian, apparently a month ago :(

https://tracker.debian.org/pkg/l3afpad

I do like it except unlike gedit I can't do new Tabs (CTRL+T) for new tabs :( , FWIW, gedit and quite a few other text editors have that functionality.

**Comment by hoijui** [comment]
#30 is related

I'll try and take over a bit, tough I will not do more then review PRs.

Tabs is definitely not a feature that will go into l3afpad proper. the main goal of l3afpad is, to stay as simple as possible. You could implement TABs and keep it in a fork or we could have a branch for it in this repo, similar to the [`autosave`](https://github.com/hoijui/l3afpad/tree/autosave) branch (in my fork).

**Comment by hoijui** [comment]
As this is now at least somewhat maintained by me (for the moment), and none else seems interested or active, neither in a fork, I will consider this solved for now.
